"use client";

import { useEffect, useState } from "react";
import { useBusinessStore } from "@/lib/store/business-store";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, Trash2 } from "lucide-react";
import { formatCurrency, formatPercent } from "@/lib/utils";
import { ScenarioBarChart, ScenarioBarDatum } from "@/components/charts/scenario-bar-chart";
import { AgentReport } from "@/lib/agents/base-agent";

const SCENARIO_COLORS = ["#a78bfa", "#22d3ee", "#34d399", "#fbbf24", "#f87171"];

export default function ReportsPage() {
  const { current, previous, scenarios, deleteScenario } = useBusinessStore();
  const [ceoReport, setCeoReport] = useState<AgentReport | null>(null);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    let cancelled = false;
    async function fetchCeoBrief() {
      setLoading(true);
      try {
        const res = await fetch("/api/agents/run", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ current, previous }),
        });
        const data = await res.json();
        if (!cancelled && data.success) {
          const ceo = (data.reports as AgentReport[]).find((r) => r.agentId === "ceo");
          setCeoReport(ceo ?? null);
        }
      } finally {
        if (!cancelled) setLoading(false);
      }
    }
    fetchCeoBrief();
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [current.timestamp]);

  const comparisonData = ["revenue", "netProfit", "riskScore"].map((metricKey) => {
    const row: ScenarioBarDatum = { metric: metricKey === "revenue" ? "Revenue ($k)" : metricKey === "netProfit" ? "Profit ($k)" : "Risk /100" };
    row["Current"] = metricKey === "riskScore" ? Math.round(current.outputs.riskScore) : Math.round(current.outputs[metricKey as "revenue" | "netProfit"] / 1000);
    scenarios.forEach((s) => {
      row[s.name] = metricKey === "riskScore" ? Math.round(s.result.outputs.riskScore) : Math.round(s.result.outputs[metricKey as "revenue" | "netProfit"] / 1000);
    });
    return row;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3 print:hidden">
        <div>
          <h1 className="text-2xl font-bold text-foreground">Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">Executive summary and scenario comparisons.</p>
        </div>
        <Button onClick={() => window.print()}>
          <Download className="h-4 w-4" /> Download / Print Report
        </Button>
      </div>

      <div id="report-content" className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle>Executive Summary</CardTitle>
            <CardDescription>Generated by the CEO Agent from all specialist reports.</CardDescription>
          </CardHeader>
          <CardContent>
            {loading && <p className="text-sm text-muted-foreground">Generating summary…</p>}
            {ceoReport && (
              <div className="space-y-4">
                <p className="text-sm text-foreground/90">{ceoReport.summary}</p>
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <Stat label="Revenue" value={formatCurrency(current.outputs.revenue)} />
                  <Stat label="Net Profit" value={formatCurrency(current.outputs.netProfit)} />
                  <Stat label="Risk Score" value={`${Math.round(current.outputs.riskScore)}/100`} />
                  <Stat label="Confidence" value={`${ceoReport.confidence}%`} />
                </div>
                <div>
                  <p className="text-sm font-medium text-foreground mb-2">Recommendations</p>
                  <ul className="space-y-1.5 text-sm text-muted-foreground">
                    {ceoReport.recommendations.map((rec, i) => (
                      <li key={i}>• {rec}</li>
                    ))}
                  </ul>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Scenario Comparison</CardTitle>
            <CardDescription>{scenarios.length === 0 ? "Save scenarios from the Simulation page to compare them here." : `Comparing current state against ${scenarios.length} saved scenario(s).`}</CardDescription>
          </CardHeader>
          <CardContent>
            <ScenarioBarChart data={comparisonData} scenarioNames={["Current", ...scenarios.map((s) => s.name)]} colors={SCENARIO_COLORS} />
          </CardContent>
        </Card>

        {scenarios.length > 0 && (
          <Card className="print:hidden">
            <CardHeader>
              <CardTitle>Saved Scenarios</CardTitle>
            </CardHeader>
            <CardContent className="space-y-2">
              {scenarios.map((s) => (
                <div key={s.id} className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[0.02] px-4 py-2.5">
                  <div>
                    <p className="text-sm font-medium text-foreground">{s.name}</p>
                    <p className="text-xs text-muted-foreground">
                      Revenue {formatCurrency(s.result.outputs.revenue)} · Profit {formatCurrency(s.result.outputs.netProfit)} · Margin {formatPercent(s.result.outputs.profitMargin)}
                    </p>
                  </div>
                  <Button size="icon" variant="ghost" onClick={() => deleteScenario(s.id)}>
                    <Trash2 className="h-4 w-4 text-red-400" />
                  </Button>
                </div>
              ))}
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-xl bg-white/[0.02] border border-white/10 p-3">
      <p className="text-xs text-muted-foreground">{label}</p>
      <p className="text-lg font-bold text-foreground">{value}</p>
    </div>
  );
}
